# Generated by Django 3.1.7 on 2021-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('kind', models.CharField(max_length=100, verbose_name='Вид')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo')),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
